export default {
  0: [
    './assets/images/tabs/tab1/1.jpeg',
    './assets/images/tabs/tab1/2.jpeg',
    './assets/images/tabs/tab1/3.jpeg',
    './assets/images/tabs/tab1/4.jpeg',
    './assets/images/tabs/tab1/5.jpeg',
    './assets/images/tabs/tab1/6.jpeg',
    './assets/images/tabs/tab1/7.jpeg',
    './assets/images/tabs/tab1/8.jpeg',
  ],
  1: [
    './assets/images/tabs/tab2/1.jpeg',
    './assets/images/tabs/tab2/2.jpeg',
    './assets/images/tabs/tab2/3.jpeg',
    './assets/images/tabs/tab2/4.jpeg',
    './assets/images/tabs/tab2/5.jpeg',
    './assets/images/tabs/tab2/6.jpeg',
    './assets/images/tabs/tab2/7.jpeg',
    './assets/images/tabs/tab2/8.jpeg',
  ],
  2: [
    './assets/images/tabs/tab3/1.jpeg',
    './assets/images/tabs/tab3/2.jpeg',
    './assets/images/tabs/tab3/3.jpeg',
    './assets/images/tabs/tab3/4.jpeg',
    './assets/images/tabs/tab3/5.jpeg',
    './assets/images/tabs/tab3/6.jpeg',
    './assets/images/tabs/tab3/7.jpeg',
    './assets/images/tabs/tab3/8.jpeg',
  ],
  3: [
    './assets/images/tabs/tab4/1.jpeg',
    './assets/images/tabs/tab4/2.jpeg',
    './assets/images/tabs/tab4/3.jpeg',
    './assets/images/tabs/tab4/4.jpeg',
    './assets/images/tabs/tab4/5.jpeg',
    './assets/images/tabs/tab4/6.jpeg',
    './assets/images/tabs/tab4/7.jpeg',
    './assets/images/tabs/tab4/8.jpeg',
  ],
  4: [
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
  ],
  5: [
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
    './assets/images/tabs/tab5/1.jpeg',
  ],
};
